version: 2

sources:
  - name: info
    schema: info
    loader: SQLite CLI
    tables:
      - name: info
        description: Fact table for orders including customer and cohort dimensions.
        columns:
          - name: id
          - name: name
          - name: city
          - name: comments
