name: "Test and Build"

on: [push]

env:
    DEV_SHELL_NAME: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@v4.1.0

    - name: "Install python dependencies"
      run: poetry install
      shell: bash

    - name: "Test"
      run: poetry run python -m unittest tests/recognizer/flair_recognizer_test.py
      shell: bash
