name: Test and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: ./setup.sh
      shell: bash

    - name: Install python dependencies
      run: poetry install
      shell: bash

    - name: Test
      run: poetry run python -m unittest tests/**.py
      shell: bash
